version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-un+1-(kllp1)5i#wu^=e33h#+q-w4$d5c7*ijl@^l@75y6$af8
      - DATABASE_URL=postgres://user:password@db:5432/meshzen_db
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=meshzen_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
