version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=your_secret_key_here
      - DATABASE_URL=postgres://user:password@db:5432/meshzen_db
    depends_on:
      - db
    environment:
      - http_proxy
      - https_proxy
    networks:
      - backend

  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=meshzen_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

  pypicache:
    image: pypicache
    ports:
      - "3141:3141"
    volumes:
      - pypicache:/data/pypi
    environment:
      - http_proxy
      - https_proxy
    networks:
      - backend

volumes:
  postgres_data:
  pypicache:

networks:
  backend:
    driver: bridge
