# Generated by Django 4.1.7 on 2023-03-07 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeshFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('download_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ZenodoDeposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('deposition_id', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('created_date', models.DateTimeField()),
                ('published_date', models.DateTimeField()),
                ('spine_mesh_files', models.ManyToManyField(to='meshes.meshfile')),
            ],
        ),
        migrations.AddField(
            model_name='meshfile',
            name='deposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meshes.zenododeposition'),
        ),
    ]
